### ISSUE TITLE
"input.size(1) != 3" and "if input.size(1) != 784"    problem

### ISSUE THREAD

**Issue by Aebestach** [itayhubara/BinaryNet.pytorch#28]
> binarized_modules.py
Hello, the author, I have some code in this document, I want to express anything else.
`input.size(1) != 784` in the binarizelinear class,`input.size(1) != 3`in the BinarizeConv2D class. 
What do they want to express?

**Comment by itayhubara** [comment]
You can't binarize the input image so if the size is 784 (for MNIST) or size(1)=3 for any RGB image (i.e. Cifar10 ImageNet) then you don't binarize the input.
